// <auto-generated />
using MLE_Infobot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MLE_Infobot.Migrations
{
    [DbContext(typeof(LeagueDBContext))]
    [Migration("20260528023157_MappingValIntToLong")]
    partial class MappingValIntToLong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("MLE_Infobot.Division", b =>
                {
                    b.Property<int>("DivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DivisionId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Division");
                });

            modelBuilder.Entity("MLE_Infobot.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("AwayPlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayPlayerWins")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("HomePlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomePlayerWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId");

                    b.HasIndex("MatchId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("MLE_Infobot.MappingVal", b =>
                {
                    b.Property<int>("MappingValId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("MappingValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MappingValId");

                    b.HasIndex("WeekId");

                    b.ToTable("MappingVal");
                });

            modelBuilder.Entity("MLE_Infobot.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwaySquadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeSquadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Winner")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchId");

                    b.HasIndex("AwaySquadId");

                    b.HasIndex("HomeSquadId");

                    b.HasIndex("WeekId");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("MLE_Infobot.PlayerName", b =>
                {
                    b.Property<int>("PlayerNameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("PlayerUserID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerNameId");

                    b.ToTable("PlayerNames");
                });

            modelBuilder.Entity("MLE_Infobot.PlayerSquadPlayer", b =>
                {
                    b.Property<int>("PlayerSquadPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("PlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SquadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SquadPlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerSquadPlayerId");

                    b.HasIndex("SquadId");

                    b.ToTable("PlayerSquadPlayer");
                });

            modelBuilder.Entity("MLE_Infobot.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("SeasonId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("MLE_Infobot.Squad", b =>
                {
                    b.Property<int>("SquadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DivisionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SquadNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SquadId");

                    b.HasIndex("DivisionId");

                    b.HasIndex("TeamId");

                    b.ToTable("Squad");
                });

            modelBuilder.Entity("MLE_Infobot.SubstituteSquadPlayer", b =>
                {
                    b.Property<int>("SubstituteSquadPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("PlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SquadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SquadPlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SubstituteSquadPlayerId");

                    b.HasIndex("SquadId");

                    b.ToTable("SubstituteSquadPlayer");
                });

            modelBuilder.Entity("MLE_Infobot.Substitution", b =>
                {
                    b.Property<int>("SubstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("PlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SubstituteID")
                        .HasColumnType("INTEGER");

                    b.HasKey("SubstitutionId");

                    b.HasIndex("MatchId");

                    b.ToTable("Substitution");
                });

            modelBuilder.Entity("MLE_Infobot.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TeamCaptainID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamLogoURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("TeamRoleID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Unlinked")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("MLE_Infobot.Week", b =>
                {
                    b.Property<int>("WeekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasBeenGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("WeekId");

                    b.ToTable("Week");

                    b.HasDiscriminator().HasValue("Week");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MLE_Infobot.PlayoffWeek", b =>
                {
                    b.HasBaseType("MLE_Infobot.Week");

                    b.Property<int>("PlayoffWeekId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("SeasonId");

                    b.HasDiscriminator().HasValue("PlayoffWeek");
                });

            modelBuilder.Entity("MLE_Infobot.SeasonWeek", b =>
                {
                    b.HasBaseType("MLE_Infobot.Week");

                    b.Property<bool>("IsOnlyPartiallyFilled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonWeekId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("SeasonId");

                    b.HasDiscriminator().HasValue("SeasonWeek");
                });

            modelBuilder.Entity("MLE_Infobot.Division", b =>
                {
                    b.HasOne("MLE_Infobot.Season", "Season")
                        .WithMany("Divisions")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("MLE_Infobot.Game", b =>
                {
                    b.HasOne("MLE_Infobot.Match", "Match")
                        .WithMany("Games")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("MLE_Infobot.MappingVal", b =>
                {
                    b.HasOne("MLE_Infobot.Week", "Week")
                        .WithMany("Players123Mappings")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Week");
                });

            modelBuilder.Entity("MLE_Infobot.Match", b =>
                {
                    b.HasOne("MLE_Infobot.Squad", "AwaySquad")
                        .WithMany()
                        .HasForeignKey("AwaySquadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MLE_Infobot.Squad", "HomeSquad")
                        .WithMany()
                        .HasForeignKey("HomeSquadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MLE_Infobot.Week", "Week")
                        .WithMany("Matches")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwaySquad");

                    b.Navigation("HomeSquad");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("MLE_Infobot.PlayerSquadPlayer", b =>
                {
                    b.HasOne("MLE_Infobot.Squad", "Squad")
                        .WithMany("PlayerIDs")
                        .HasForeignKey("SquadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Squad");
                });

            modelBuilder.Entity("MLE_Infobot.Squad", b =>
                {
                    b.HasOne("MLE_Infobot.Division", "Division")
                        .WithMany("Squads")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MLE_Infobot.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("MLE_Infobot.SubstituteSquadPlayer", b =>
                {
                    b.HasOne("MLE_Infobot.Squad", "Squad")
                        .WithMany("SubstituteIDs")
                        .HasForeignKey("SquadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Squad");
                });

            modelBuilder.Entity("MLE_Infobot.Substitution", b =>
                {
                    b.HasOne("MLE_Infobot.Match", "Match")
                        .WithMany("Substitutions")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("MLE_Infobot.PlayoffWeek", b =>
                {
                    b.HasOne("MLE_Infobot.Season", "Season")
                        .WithMany("PlayoffWeeks")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("MLE_Infobot.SeasonWeek", b =>
                {
                    b.HasOne("MLE_Infobot.Season", "Season")
                        .WithMany("SeasonWeeks")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("MLE_Infobot.Division", b =>
                {
                    b.Navigation("Squads");
                });

            modelBuilder.Entity("MLE_Infobot.Match", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Substitutions");
                });

            modelBuilder.Entity("MLE_Infobot.Season", b =>
                {
                    b.Navigation("Divisions");

                    b.Navigation("PlayoffWeeks");

                    b.Navigation("SeasonWeeks");
                });

            modelBuilder.Entity("MLE_Infobot.Squad", b =>
                {
                    b.Navigation("PlayerIDs");

                    b.Navigation("SubstituteIDs");
                });

            modelBuilder.Entity("MLE_Infobot.Week", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Players123Mappings");
                });
#pragma warning restore 612, 618
        }
    }
}
