// <auto-generated />
using MLE_Infobot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MLE_Infobot.Migrations
{
    [DbContext(typeof(LeagueDBContext))]
    [Migration("20260311224257_Leaguev0-0-1")]
    partial class Leaguev001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("MLE_Infobot.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("AwayPlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayPlayerWins")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("HomePlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomePlayerWins")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatchId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId");

                    b.HasIndex("MatchId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("MLE_Infobot.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwaySquadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeSquadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchId");

                    b.HasIndex("AwaySquadId");

                    b.HasIndex("HomeSquadId");

                    b.HasIndex("WeekId");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("MLE_Infobot.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfSeasonWeeks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("SeasonId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("MLE_Infobot.Squad", b =>
                {
                    b.Property<int>("SquadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SquadId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId");

                    b.ToTable("Squad");
                });

            modelBuilder.Entity("MLE_Infobot.Substitution", b =>
                {
                    b.Property<int>("SubstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("PlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SubstituteID")
                        .HasColumnType("INTEGER");

                    b.HasKey("SubstitutionId");

                    b.HasIndex("MatchId");

                    b.ToTable("Substitution");
                });

            modelBuilder.Entity("MLE_Infobot.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TeamCaptainID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamLogoURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("TeamRoleID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Unlinked")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("MLE_Infobot.Week", b =>
                {
                    b.Property<int>("WeekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("WeekId");

                    b.ToTable("Week");

                    b.HasDiscriminator().HasValue("Week");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MLE_Infobot.PlayoffWeek", b =>
                {
                    b.HasBaseType("MLE_Infobot.Week");

                    b.HasIndex("SeasonId");

                    b.HasDiscriminator().HasValue("PlayoffWeek");
                });

            modelBuilder.Entity("MLE_Infobot.SeasonWeek", b =>
                {
                    b.HasBaseType("MLE_Infobot.Week");

                    b.HasIndex("SeasonId");

                    b.HasDiscriminator().HasValue("SeasonWeek");
                });

            modelBuilder.Entity("MLE_Infobot.Game", b =>
                {
                    b.HasOne("MLE_Infobot.Match", null)
                        .WithMany("Games")
                        .HasForeignKey("MatchId");
                });

            modelBuilder.Entity("MLE_Infobot.Match", b =>
                {
                    b.HasOne("MLE_Infobot.Squad", "AwaySquad")
                        .WithMany()
                        .HasForeignKey("AwaySquadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MLE_Infobot.Squad", "HomeSquad")
                        .WithMany()
                        .HasForeignKey("HomeSquadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MLE_Infobot.Week", "Week")
                        .WithMany("Matches")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwaySquad");

                    b.Navigation("HomeSquad");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("MLE_Infobot.Squad", b =>
                {
                    b.HasOne("MLE_Infobot.Season", "Season")
                        .WithMany("Squads")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MLE_Infobot.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("MLE_Infobot.Substitution", b =>
                {
                    b.HasOne("MLE_Infobot.Match", null)
                        .WithMany("Substitutions")
                        .HasForeignKey("MatchId");
                });

            modelBuilder.Entity("MLE_Infobot.PlayoffWeek", b =>
                {
                    b.HasOne("MLE_Infobot.Season", "Season")
                        .WithMany("PlayoffWeeks")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("MLE_Infobot.SeasonWeek", b =>
                {
                    b.HasOne("MLE_Infobot.Season", "Season")
                        .WithMany("SeasonWeeks")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("MLE_Infobot.Match", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Substitutions");
                });

            modelBuilder.Entity("MLE_Infobot.Season", b =>
                {
                    b.Navigation("PlayoffWeeks");

                    b.Navigation("SeasonWeeks");

                    b.Navigation("Squads");
                });

            modelBuilder.Entity("MLE_Infobot.Week", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
