// <auto-generated />
using MLE_Infobot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MLE_Infobot.Migrations
{
    [DbContext(typeof(LeagueDBContext))]
    partial class LeagueDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");
#pragma warning restore 612, 618
        }
    }
}
